//
// Created by vgol on 07/01/2024.
//

#ifndef QEMU_NRF52_WRAPPER_NRF5X_RADIO_H
#define QEMU_NRF52_WRAPPER_NRF5X_RADIO_H

#include "hw/sysbus.h"
#include "qemu/timer.h"
#include "qom/object.h"
#include "hw/registerfields.h"

#define NRF_RADIO_PER_SIZE   0x1000

REG32(RADIO_TASKS_TXEN, 0x000)
REG32(RADIO_TASKS_RXEN, 0x004)
REG32(RADIO_TASKS_START, 0x008)
REG32(RADIO_TASKS_STOP, 0x00C)
REG32(RADIO_TASKS_DISABLE, 0x010)
REG32(RADIO_TASKS_RSSISTART, 0x014)
REG32(RADIO_TASKS_RSSISTOP, 0x018)
REG32(RADIO_TASKS_BCSTART, 0x01C)
REG32(RADIO_TASKS_BCSTOP, 0x020)

REG32(RADIO_EVENT_READY, 0x100)
REG32(RADIO_EVENT_ADDRESS, 0x104)
REG32(RADIO_EVENT_PAYLOAD, 0x108)
REG32(RADIO_EVENT_END, 0x10C)
REG32(RADIO_EVENT_DISABLED, 0x110)
REG32(RADIO_EVENT_DEVMATCH, 0x114)
REG32(RADIO_EVENT_DEVMISS, 0x118)
REG32(RADIO_EVENT_RSSIEND, 0x11C)

REG32(RADIO_EVENT_BCMATCH, 0x128)

REG32(RADIO_SHORTS, 0x200)
    FIELD(RADIO_SHORTS, READY_START, 0, 1)
    FIELD(RADIO_SHORTS, END_DISABLE, 1, 1)
    FIELD(RADIO_SHORTS, DISABLED_TXEN, 2, 1)
    FIELD(RADIO_SHORTS, DISABLED_RXEN, 3, 1)
    FIELD(RADIO_SHORTS, ADDRESS_RSSISTART, 4, 1)
    FIELD(RADIO_SHORTS, END_START, 5, 1)
    FIELD(RADIO_SHORTS, ADDRESS_BCSTART, 6, 1)
    FIELD(RADIO_SHORTS, DISABLED_RSSISTOP, 8, 1)

REG32(RADIO_INTEN, 0x300)
    FIELD(RADIO_INTEN, READY, 0, 1)
    FIELD(RADIO_INTEN, ADDRESS, 1, 1)
    FIELD(RADIO_INTEN, PAYLOAD, 2, 1)
    FIELD(RADIO_INTEN, END, 3, 1)
    FIELD(RADIO_INTEN, DISABLED, 4, 1)
    FIELD(RADIO_INTEN, DEVMATCH, 5, 1)
    FIELD(RADIO_INTEN, DEVMISS, 6, 1)
    FIELD(RADIO_INTEN, RSSIEND, 7, 1)
    FIELD(RADIO_INTEN, BCMATCH, 10, 1)
REG32(RADIO_INTENSET, 0x304)
REG32(RADIO_INTENCLR, 0x308)

REG32(RADIO_PACKETPTR, 0x504)
REG32(RADIO_FREQUENCY, 0x508)
REG32(RADIO_TXPOWER, 0x50C)
REG32(RADIO_MODE, 0x510)

REG32(RADIO_CRCPOLY, 0x538)

REG32(RADIO_STATE, 0x550)

REG32(RADIO_DATAWHITEIV, 0x554)

REG32(RADIO_POWER, 0xFFC)

#define TYPE_NRF_RADIO "nrf_soc.radio"
OBJECT_DECLARE_SIMPLE_TYPE(NRF5RADIOState, NRF_RADIO)

struct NRF5RADIOState {
    SysBusDevice parent_obj;

    MemoryRegion iomem;
    qemu_irq irq;

//    uint8_t id;

    QEMUTimer per_int;

//    bool enabled;
//    bool running;

    uint32_t regs[NRF_RADIO_PER_SIZE];

    MemoryRegion *downstream;
    AddressSpace downstream_as;
};

#endif //QEMU_NRF52_WRAPPER_NRF5X_RADIO_H
